LITELUA_SCRIPTS_FOLDER=$(dirname "$0")

LITELUA_DIR="$LITELUA_SCRIPTS_FOLDER/.."

LITELUA_OUTPUT="$LITELUA_DIR/output"
LITELUA_BUILD_DIR="$LITELUA_DIR/build"

mkdir -p $LITELUA_BUILD_DIR
mkdir -p $LITELUA_OUTPUT
